[package]
name = "kademlia-plus-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
sha1="^0.10.0"
tokio = { version = "1", features = ["full"] }
rand="0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono="^0.4"
